apiVersion: batch/v1
kind: Job
metadata:
  name: minio-job
spec:
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc
        command: ["/bin/sh", "-c"]
        args:
          - >
            sleep 10;
            mc alias set myminio http://minio-service:9000 minio minio123;
            mc mb myminio/mybucket;
            mc ls myminio;
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_PASSWORD
      restartPolicy: Never